# This is a basic workflow to help you get started with Actions

name: Update plot once a week

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 12 * * 4"
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get older data
        run: curl https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Sterbefaelle-Lebenserwartung/Tabellen/sonderauswertung-sterbefaelle-endgueltige-daten.xlsx?__blob=publicationFile -o sonderauswertung-sterbefaelle-endgueltige-daten.xlsx
      
      - name: Get current data
        run: curl https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Sterbefaelle-Lebenserwartung/Tabellen/sonderauswertung-sterbefaelle.xlsx?__blob=publicationFile -o sonderauswertung-sterbefaelle.xlsx

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build plot
        run: python plot.py
        
      - name: upload artifact 
        uses: actions/upload-artifact@v3
        with:
          name: mortality
          path: mortality.png
          retention-days: 14
